#!/bin/bash

USER=
FILENAME=
CONTENT=
TMP_FILE=/tmp/temporary_gist_file
trap "rm ${TMP_FILE} &> /dev/null" EXIT

while getopts "f:n:c:u:" flag; do
    case ${flag} in
	f)
	    if [ ! -f ${OPTARG} ]; then
		echo "${OPTARG} does not exist. Please specify an existing filename"
		exit 1
	    else		
		FILENAME="\"$(basename ${OPTARG})\""
		CONTENT=$(awk '{print $0"\\n"}' ${OPTARG})
		CONTENT="\"$(echo ${CONTENT} | awk '{gsub(/"/, "\\\"")} 1')\""
	    fi
	    ;;
	n)
	    FILENAME="\"${OPTARG}\""
	    ;;
	c)
	    CONTENT="\"${OPTARG}\""
	    ;;
	u)
	    USER="--user ${OPTARG}"
	    ;;
	*)
	    exit 1
	    ;;
	    
    esac
done

echo "{\"files\": {${FILENAME}: {\"content\": ${CONTENT}}}}" > ${TMP_FILE}

curl ${USER} -X POST -H 'Content-Type: application/json' -d @${TMP_FILE} https://api.github.com/gists
